feat(UIKIT-734): Реализован pattern
kaluga-astral/revizor pull request #22
Opened 2023-05-16 13:04 UTC by yar-stun

- [ ] Написать тесты

2023-05-16 13:26 UTC, AndTem requested changes

2023-05-16 13:26 UTC, AndTem commented on package/src/pattern/pattern.ts
> +export const pattern = <ValidationType extends PatternValidationTypes>(
ValidationType здесь не имеет смысла принимать параметром, а вот TValues надо.
createRule<string, TValues>

2023-05-16 13:26 UTC, AndTem commented on package/src/pattern/pattern.ts
> +export const pattern = <ValidationType extends PatternValidationTypes>(
jsdoc описание необходимо по аналогии с другими правилами

2023-05-16 13:26 UTC, AndTem commented on package/src/pattern/pattern.ts
> +export const pattern = <ValidationType extends PatternValidationTypes>(
Нужны тесты

2023-05-17 08:09 UTC, StanislavDa approved these changes

2023-05-17 08:11 UTC, merged